POST http://localhost:4000/transactions
Content-Type: application/json

{
    "paymentMethod": "debit_card",
    "cardNumber": "444411112222",
    "amount": 3000,
    "paymentDate": "05-03-2022",
    "barcode": "123456789224"
}