POST http://localhost:4000/payables
Content-Type: application/json

{
    "serviceType": "Agua",
    "description": "AySA",
    "dueDate": "05-25-2022",
    "amount": 680,
    "barcode": 623452789214,
    "status": "pending"
}